config/routes.rb
Rails.application.routes.draw do

  resources :password_resets

  get 'password_resets/new'

  get 'picks/' => "picks#like"
  post 'picks/' => "picks#like"

  get 'options/' => "options#show"
  post 'options/new' => "posts#create"

  get 'users/index'

  get "users/new" => "users#new", as: :new_user
  get "users/:id" => "users#show", as: :user
  post "users/" => "users#create"
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy"

  get "posts/" => "posts#index"
  get "posts/new" => "posts#new", as: :new_post
  get "posts/:id" => "posts#show", as: :post
  post "posts/new" => "posts#create"
  delete "posts/:id" => "posts#destroy", as: :post_delete

  get "signup/" => "users#new"
  get "login/" => "sessions#new"
  post "login/" => "sessions#create"
  delete "logout/" => "sessions#destroy"

  root 'posts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :picks
  has_many :picked_options, :through => :picks, :source => :option

#validates handle/email are not duplicates, and all info is present and of
#proper length and format

  validates_uniqueness_of :handle, :email, case_sensitive: false, :message =>
  "THAT USERNAME AND/OR EMAIL HAS ALREADY BEEN TAKEN"
  validates :handle, :fname, :lname, :email, presence: true
  validates :handle, :fname, :lname, length: {in: 1...18, :message =>
  "OOPS, LOOKS LIKE YOU ENTERED TOO LONG OF A USERNAME, FIRST NAME, OR LAST NAME"}
  validates :handle, format: { with: /\A[a-zA-Z0-9]+\Z/,
    :message => "ONLY LETTERS/NUMBERS ALLOWED IN USERNAME"  }



# before a user is created, set the handle/email to downcase for login purposes

  before_create do self.handle.downcase! end
  before_create do self.email.downcase! end

  def send_password_reset
   UserMailer.password_reset(self).deliver
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#only allow edit/update to be utilized by currently logged in user, and verify
#that correct_user is attempting to edit info, thus preventing a user from
#editing a different users info

  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def index

    @users = User.all

  end

#create a time object and a headers object array to be used in user profile for
#style purposes

  def show

    @user = User.find(params[:id])

    @time = Time.new.strftime("%A")

    @headers = ["well check you out, ", "oh snap, it's ", "if i had to pikwon i'd pick you, ",
       "oh hi ", "Q: Who's the best? A: ", "100% pretty cool -> " , "Shut up and dance, ",
       "Going up on a #{@time}: "]
    # @user = User.find(params[:id])

  end

  def new

    @user = User.new

  end

#create a new user and log user in

  def create

    @user = User.create(user_params)
    session[:user_id] = @user.id
    if @user.save
      UserMailer.welcome_email(@user).deliver
      redirect_to "/posts"
      # redirect_to user_path(@user.id)
    else
      flash[:message]
      render :new
    end

  end

  def edit

    @user = User.find(params[:id])

  end

  def update

    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  def destroy

    @user = User.find(params[:id])

    @userPicks = @user.picks
    @userPicks.each do |pick|
      pick.destroy
    end
    @userPosts = @user.posts
    @userPosts.each do |post|
      post.options.second.destroy
      post.options.first.destroy
      post.destroy
    end
    @user.destroy

    redirect_to "/"

  end

  private

  def user_params
    params.require(:user).permit(:handle.downcase, :fname, :lname, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

#private method to determine the correct_user is trying to access a particular
#users edit page

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container profile">

  <h1 class="header">EDIT DETAILS</h1>

  <%= form_for(@user) do |f| %>
    <%= f.text_field :fname, :placeholder => "FIRST NAME" %><br>
    <%= f.text_field :lname, :placeholder => "LAST NAME" %><br>
    <%= f.email_field :email, :placeholder => "EMAIL" %><br>
    <%= f.text_field :handle.downcase, :placeholder => "USERNAME" %><br>
    <%= f.password_field :password, :placeholder => "PASSWORD" %><br>
    <%= f.password_field :password_confirmation, :placeholder => "VERIFY PASSWORD" %><br><br>
    <%= f.submit "CONFIRM CHANGES.", class: "btn-submit", data: { confirm: "Are you sure you want to make this change?"} %>
  <% end %>
  <br>
  <%= link_to "BACK", user_path %>
  </div>

app/views/users/index.html.erb
<% if current_user %>
<h1>Thanks for signing up <%= current_user.fname %>!</h1>
<% else %>
<h1>Have you signed up yet?</h1>
<% end %>
<%= link_to "BACK", "/" %>

app/views/users/new.html.erb
<div class="container profile">

  <h1 class="header">SIGN-UP</h1>

  <%= form_for(@user) do |f| %>
    <%= f.text_field :fname, :placeholder => "FIRST NAME" %><br>
    <%= f.text_field :lname, :placeholder => "LAST NAME" %><br>
    <%= f.email_field :email, :placeholder => "EMAIL" %><br>
    <%= f.text_field :handle.downcase, :placeholder => "USERNAME" %><br>
    <%= f.password_field :password, :placeholder => "PASSWORD" %><br>
    <%= f.password_field :password_confirmation, :placeholder => "VERIFY PASSWORD" %><br><br>
    <%= f.submit "GET PIK'IN.", class: "btn-submit" %>
  <% end %>
  <br>
  <%= link_to "BACK", "/" %>
</div>

app/views/users/show.html.erb
<!-- displays current users profile information if signed in   -->

<% if current_user == @user %>
<div class="container profile">
  <h1 class="header"><%= @headers.shuffle.first.upcase %>
    <%= current_user.fname.upcase %>.
  </h1>
  <h2>username:
    <%= current_user.handle.upcase %></h2>
  <h2>first name:
    <%= current_user.fname.upcase %></h2>
  <h2>last name:
    <%= current_user.lname.upcase %></h2>
  <h2>e-mail:
    <%= current_user.email.upcase %></h2>
  <h2>member since:
    <%= current_user.created_at.utc.strftime("%D") %></h2>

  <%= link_to "BACK TO PIK'IN", "/" %><%= link_to "EDIT", edit_user_path(current_user) %>
  <%= link_to "DELETE", user_path(current_user), method: :delete,
  data: { confirm: "Are you sure you want to delete this account?"} %>
</div>

<!-- displays current_user's post history -->

<div class="post_history_container">
  <% current_user.posts.each do |post| %>

  <div class="post_history">

    <span class="delete_container">
      <span class="delete">
        <%= link_to "X", post_delete_path(post.id), method: :delete,
  data: { confirm: "Are you sure you want to delete this post?"} %>
      </span>
    </span>

    <div class="profile_options">
      <%= post.options.first.option_text.upcase %>

<!-- uses percentage method created in picks_helper to determine percentage of picks -->

      <span class="likes"><%= percentage(post.options.first.option_picks.to_i, post.options.second.option_picks.to_i) %>
        %</span>
    </div>
    <div class="profile_options">
      <%= post.options.second.option_text.upcase %>

<!-- uses percentage method created in picks_helper to determine percentage of picks -->

      <span class="likes"><%= percentage(post.options.second.option_picks.to_i, post.options.first.option_picks.to_i) %>
        %
      </span>
    </div>
    POSTED ON:
    <%= post.created_at.utc.strftime("%D") %>
  </div>

  <% end %>
</div>

<% else %>
<div class="container profile">
  <h1 class="header"><%= @user.handle.upcase %>'S POSTS.</h1>
  <%= link_to "BACK TO PIK'IN", posts_path %><br>
</div>
<div class="post_history_container">
  <% @user.posts.each do |post| %>

  <div class="post_history">

    <div class="profile_options">
      <%= post.options.first.option_text.upcase %>

<!-- uses percentage method created in picks_helper to determine percentage of picks -->

      <span class="likes"><%= percentage(post.options.first.option_picks.to_i, post.options.second.option_picks.to_i) %>
        %</span>
    </div>
    <div class="profile_options">
      <%= post.options.second.option_text.upcase %>

<!-- uses percentage method created in picks_helper to determine percentage of picks -->

      <span class="likes"><%= percentage(post.options.second.option_picks.to_i, post.options.first.option_picks.to_i) %>
        %
      </span>
    </div>
    POSTED ON:
    <%= post.created_at.utc.strftime("%D") %>
  </div>

  <% end %>
</div>

<% end %>

<!-- JS -->

<script>
// initializes count to current users posts * 2

var count = <%= @user.posts.count * 2 %>
for (var i = 0, j = 0; i < count; i += 2, j++) {

// grabs percentage values that are stored within elements

  var first = document.getElementsByClassName("likes")[i].innerHTML.toString()
  var second = document.getElementsByClassName("likes")[i + 1].innerHTML.toString() // uses percentage values to update gradient styles to options

  document.getElementsByClassName("profile_options")[i].style.background = "linear-gradient(to right, rgb(94, 94, 92) 0%, rgb(94, 94, 92) " + parseInt(first) + "%, #3dd9da " + parseInt(first) + "%, #3dd9da 100%)";
  document.getElementsByClassName("profile_options")[i + 1].style.background = "linear-gradient(to right, rgb(94, 94, 92) 0%, rgb(94, 94, 92) " + parseInt(second) + "%, #3dd9da " + parseInt(second) + "%, #3dd9da 100%)";

  var test = document.getElementsByClassName("post_history")[j];

// function showDelete that is displayed upon hovering over profile options

  function showDelete() {
    this.getElementsByClassName("delete")[0].style.display = "block";
  }

// function hideDelete that is hidden when no longer hovering over profile options

  function hideDelete() {
    this.getElementsByClassName("delete")[0].style.display = "none";
  }

// add eventlisteners to proper elements

  test.addEventListener("mouseover", showDelete)
  test.addEventListener("mouseout", hideDelete)
}
</script>