config/routes.rb
Rails.application.routes.draw do

  resources :password_resets

  get 'password_resets/new'

  get 'picks/' => "picks#like"
  post 'picks/' => "picks#like"

  get 'options/' => "options#show"
  post 'options/new' => "posts#create"

  get 'users/index'

  get "users/new" => "users#new", as: :new_user
  get "users/:id" => "users#show", as: :user
  post "users/" => "users#create"
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy"

  get "posts/" => "posts#index"
  get "posts/new" => "posts#new", as: :new_post
  get "posts/:id" => "posts#show", as: :post
  post "posts/new" => "posts#create"
  delete "posts/:id" => "posts#destroy", as: :post_delete

  get "signup/" => "users#new"
  get "login/" => "sessions#new"
  post "login/" => "sessions#create"
  delete "logout/" => "sessions#destroy"

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :options, dependent: :destroy
  belongs_to :user, :class_name => User, :foreign_key => "user_id"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #requre a user being logged in to create a post

  before_action :require_user, only: [:new, :create]

  def index

    @posts = Post.all
    @options = Option.all

  end

  def show

    @post = Post.find(params[:id])

  end

  def new

    @post = Post.new

  end

  def create

#create new post object

    @post = Post.new

#check to see if options input are duplicates, render new if so to prevent duplicates

    if params[:test][:option_text_one].strip == params[:test][:option_text_two].strip

      render :new

#else create post with options

    else

#create option and shovel option into post, do this twice with both options

      @option = Option.new(:option_text => params[:test][:option_text_one])

      @post.options << @option

      @option = Option.new(:option_text => params[:test][:option_text_two])

      @post.options << @option

      @post.user_id = current_user.id

#if post is saved with no errors, redirect to posts, else render new

      if @option.save
        @post.save
        redirect_to posts_path
      else
        redirect_to new_post_path
      end
    end

  end

#destroy post and all picks/options associated with it, and redirect to user profile

  def destroy
    @post = Post.find(params[:id])
    @option1picks = @post.options.second.picks
    @option2picks = @post.options.first.picks
    @option1 = @post.options.first
    @option2 = @post.options.second
    @option1picks.destroy
    @option2picks.destroy
    @option1.destroy
    @option2.destroy
    @post.destroy

    redirect_to user_path(current_user.id)
  end

#create option/post params

  private

  def post_params
    params.require(:post).permit(:option_ids => [])
  end

  def option_params
    params.require(:option).permit(:option_text, :post_ids => [])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="container">

  <div class="logo">
    <span class ="character"></span>
    <span class ="character"></span>
    <span class ="character"></span>
  </div>

<!-- checks to see if current_user exists -->

<% if current_user %>

<!-- Finding all posts that were not created by current_user if current_user exists
and posts current_user hasnt picked on, and places those in available_posts
in order to be iterated through  -->

  <% @available_posts = []

  @posts.each do |post|

    if post.user_id == current_user.id or
      current_user.picks.where(:post_id => post.id).count > 0
    else
      @available_posts << post
    end
  end

  %>

<!-- if available_posts count == 0, lets user know they've reached the end -->

  <% if @available_posts.count == 0 %>

  <div class="options_container">

    <div class="options">

    YOU'VE REACHED THE END.

    </div>
  </div>


  <span class="new">
    <%= link_to "NEW", new_post_path %>
  </span>
  <div class="options_container">

    <div class="options">

      COME BACK LATER!

    </div>
  </div>

<!-- else it iterates randomly through available_posts allowing user to pick which
option they'd prefer -->

  <% else %>

    <% @available_posts.sample(1).each do |post| %>

  <div class="options_container">
    <div class="test_likes">
      <%= post.options.first.option_picks %>
    </div>
    <div class="options">

      <%= button_to post.options.first.option_text.upcase, picks_path(:id => post.options.first.id,
      :post => post.id, :skip => false), data: {disable_with: post.options.first.option_text.upcase} %>

    </div>
    <div class="test_likes">
    </div>
  </div>
  <span class="new">
    POSTED BY: <%= link_to User.find(post.user_id).handle.upcase, user_path(:id => post.user_id) %>
  </span>
  <div class="options_container">
    <div class="test_likes">
      <%= post.options.second.option_picks %>
    </div>
    <div class="options">

      <%= button_to post.options.second.option_text.upcase, picks_path(:id => post.options.second.id,
      :post => post.id, :skip => false), data: {disable_with: post.options.second.option_text.upcase} %>

    </div>
    <div class="test_likes">
    </div>
  </div>
  <div class="skip">
    <%= button_to "SKIP\nWON",
    picks_path(:id => post.options.first.id,
    :post => post.id, :skip => true), data: {disable_with: "SKIP\nWON"} %>
  </div>


  <% end %>


<% end %>

<!-- else current_user doesn't exist and loads random post which directs to signup -->

<% else %>

  <% @posts.all.sample(1).each do |post| %>
  <div class="options_container">

    <div class="options">

      <%= button_to post.options.first.option_text.upcase, picks_path(:id => post.options.first.id,
      :post => post.id) %>

    </div>
  </div>
  <span class="new">
    POSTED BY: <%= User.find(post.user_id).handle.upcase %>
  </span>
  <div class="options_container">

    <div class="options">

      <%= button_to post.options.second.option_text.upcase, picks_path(:id => post.options.second.id,
      :post => post.id) %>

    </div>
  </div>

  <% end %>
<% end %>

  <div class="logo">
    <span class ="character"></span>
    <span class ="character"></span>
    <span class ="character"></span>
  </div>

</div>

<script>

var optionOne = document.getElementsByClassName("options_container")[0];
var optionTwo = document.getElementsByClassName("options_container")[1];
var optionOneLink = document.getElementsByClassName("options")[0];
var optionTwoLink = document.getElementsByClassName("options")[1];
var clicked = false;

// showPercentages function in order to add animation to user click and display
// current statistics on post picks

function showPercentages(a, b){

// checks to make sure element hasn't been clicked yet do prevent multiple clicks

  if(!clicked){
    return function() {
      console.log("hi");

// sets initial values to pick value, mimicing the users pick by adding 1 to the
// value of the element they chose in order to display proper percentages

      var first = parseInt(document.getElementsByClassName("test_likes")[0].innerHTML) + b;
      var second = parseInt(document.getElementsByClassName("test_likes")[2].innerHTML) + a;

      // console.log(first)
      // console.log(second)

// takes the percentage of the first options picks and second options picks

      var percentageTop = Math.round((parseInt(first) / (parseInt(first) + parseInt(second))) * 100);
      var percentageBottom = Math.round((parseInt(second) / (parseInt(second) + parseInt(first))) * 100);

      // console.log(percentageTop)
      // console.log(percentageBottom)

// adds a class to the options that allow for display transition properties


// changes each options background to a gradient based on the percentage of picks
// chosen for each particular option, and sets a transition for animation effect

      optionOne.style.background = "linear-gradient(to right, rgb(94, 94, 92) 0%, rgb(94, 94, 92) "
       + parseInt(percentageTop) + "%, #25acb6 " + parseInt(percentageTop) + "%, #25acb6 100%)";
       optionOne.style.transition = "background .75s ease";
      optionTwo.style.background = "linear-gradient(to right, rgb(94, 94, 92) 0%, rgb(94, 94, 92) "
       + parseInt(percentageBottom) + "%, #25acb6 " + parseInt(percentageBottom) + "%, #25acb6 100%)";
       optionTwo.style.transition = "background .75s ease";

// adds percentage value to be displayed

       document.getElementsByClassName("test_likes")[0].textContent = percentageTop + "%";
       document.getElementsByClassName("test_likes")[2].textContent = percentageBottom + "%";

       console.log(document.getElementsByClassName("test_likes")[0].innerHTML);

       document.getElementsByClassName("test_likes")[0].style.display = "block";
       document.getElementsByClassName("test_likes")[1].style.display = "block";
       document.getElementsByClassName("test_likes")[2].style.display = "block";
       document.getElementsByClassName("test_likes")[3].style.display = "block";

       optionOne.className += " testClass";
       optionTwo.className += " testClass";

       console.log(optionOne.className);

    }
  }
}

// adds event listeners to desired elements, passing in values that will be returned
// in showPercentages function

optionOneLink.addEventListener("click", showPercentages(0,1))
optionTwoLink.addEventListener("click", showPercentages(1,0))


</script>

app/views/posts/new.html.erb
<div class ="container">
  <div class="logo">
    <span class ="character"></span>
    <span class ="character"></span>
    <span class ="character"></span>
  </div>

<%= form_for :test, :html => { :class => "form" } do |f| %>


  <div class="options_new">
    <span class="character_count">
      22
    </span>
    <%= f.text_field :option_text_one, autocomplete: :off %>
  </div>
  <div>
    <%= f.submit "SUBMIT FOR PIKS" %>
    <span class="new">
    <%= link_to "BACK", posts_path %>
    </span>
  </div>

  <div class="options_new">
    <span class="character_count">
      22
    </span>
     <%= f.text_field :option_text_two, autocomplete: :off %>
  </div>

<% end %>
  <div class="logo">
    <span class ="character"></span>
    <span class ="character"></span>
    <span class ="character"></span>
  </div>
</div>
<script>

var firstOption = document.getElementById('test_option_text_one')
var secondOption = document.getElementById('test_option_text_two')

firstOption.addEventListener("keyup",function(){
  document.getElementsByClassName("character_count")[0].innerText = 22 - firstOption.value.length
});
secondOption.addEventListener("keyup",function(){
  document.getElementsByClassName("character_count")[1].innerText = 22 - secondOption.value.length
});

</script>

app/views/posts/test.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div class="email_container">

    <div class="email_logo">
      <a href="http://pikwon.herokuapp.com/"><%= image_tag("pikwonlogo.png") %></a>
    </div>
    <div class="email_body">

    <h1>HEY CHRIS!</h1>
    <p>
      Why am I yelling at you? I'm just excited to be e-mailing you that's all!
      Thank you oh so kindly for signing up for <a href="http://pikwon.herokuapp.com/">Pikwon</a>, we're thrilled to have you!
      <br><br>
      If you have any questions or comments whatsoever, feel free to give us a shout
      (preferably a polite shout, but it's up to you...)
      <br><br>
       Until then, go ahead and Pikwon, and then pik one more!
      <br><br>
      Chris Garvin
      <br>
      <a href="mailto:name@email.com">Chris@pikwon.com</a>
    </p>

  </div>
</div>
  </body>
</html>