config/routes.rb
Rails.application.routes.draw do

  resources :password_resets

  get 'password_resets/new'

  get 'picks/' => "picks#like"
  post 'picks/' => "picks#like"

  get 'options/' => "options#show"
  post 'options/new' => "posts#create"

  get 'users/index'

  get "users/new" => "users#new", as: :new_user
  get "users/:id" => "users#show", as: :user
  post "users/" => "users#create"
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy"

  get "posts/" => "posts#index"
  get "posts/new" => "posts#new", as: :new_post
  get "posts/:id" => "posts#show", as: :post
  post "posts/new" => "posts#create"
  delete "posts/:id" => "posts#destroy", as: :post_delete

  get "signup/" => "users#new"
  get "login/" => "sessions#new"
  post "login/" => "sessions#create"
  delete "logout/" => "sessions#destroy"

  root 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>pikwon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:700' rel='stylesheet' type='text/css'>
  <meta name=viewport content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-title" content="pikwon" />
  <meta name="apple-mobile-web-app-status-bar-style" content="#3dd9da" />
  <link rel="apple-touch-icon" href="assets/pikwonlogosquare.png" />
</head>
<body>
  <header class="logout">
  <% if current_user %>
<ul>
  <li><%= link_to current_user.handle.upcase, user_path(:id => current_user.id) %> <span class="primary">|</span></li>
  <li>
    <%= link_to "NEW", new_post_path %> <span class="primary">|</span>
  </li>
  <li><%= link_to "Log out".upcase, logout_path, method: "delete" %></li>
</ul>
  <% else %>
    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.text_field :handle.downcase, :placeholder => "Username".upcase %>
      <%= f.password_field :password, :placeholder => "Password".upcase %>
      <%= f.submit "Log in".upcase, class: "btn-submit" %>
      <%= link_to "Sign-up".upcase, new_user_path %> <h3 style="display:inline;">|</h3>
      <%= link_to "FORGOT PASSWORD", new_password_reset_path %>
    <% end %>
<% end %>
</header>

<%= yield %>
<!-- <footer class='footer'>
  Copyright &copy; 2015 Chris Garvin <br>
</footer> -->
</body>
</html>